#pragma once

#include "driver/gpio.h"

#define APP_NAME "habit_tracker_esp32s3"

#define HABIT_COUNT 3
#define DEFAULT_DURATION_SECONDS (20 * 60)
#define MIN_DURATION_SECONDS 60
#define MAX_DURATION_SECONDS (99 * 60)

#define MAX7219_DIN_PIN GPIO_NUM_4
#define MAX7219_CLK_PIN GPIO_NUM_5
#define MAX7219_CS_PIN GPIO_NUM_6
#define MAX7219_DEVICE_COUNT 4
#define MAX7219_DEFAULT_INTENSITY 2

#define HABIT_LED_1_PIN GPIO_NUM_15
#define HABIT_LED_2_PIN GPIO_NUM_16
#define HABIT_LED_3_PIN GPIO_NUM_17

#define BUTTON_LEFT_PIN GPIO_NUM_7
#define BUTTON_PLAY_PIN GPIO_NUM_8
#define BUTTON_RIGHT_PIN GPIO_NUM_9

#define BUTTON_DEBOUNCE_MS 40
#define BUTTON_LONG_PRESS_MS 700
#define MAIN_LOOP_DELAY_MS 10
#define FINISHED_BLINK_MS 300
