#pragma once

#include "driver/gpio.h"

#define APP_NAME "tickstone"

#define OLED_SDA_PIN GPIO_NUM_7
#define OLED_SCL_PIN GPIO_NUM_6
#define OLED_I2C_ADDRESS 0

#define BUTTON_LEFT_PIN GPIO_NUM_20
#define BUTTON_PLAY_PIN GPIO_NUM_8
#define BUTTON_RIGHT_PIN GPIO_NUM_9

#define BUTTON_DEBOUNCE_MS 40
#define BUTTON_LONG_PRESS_MS 700
#define BUTTON_ACTIVE_LOOP_DELAY_MS 10
#define SESSION_LOOP_DELAY_MS 100
#define IDLE_LOOP_DELAY_MS 150
#define FINISHED_BLINK_MS 300

#define OLED_FULL_CONTRAST 0x80
#define OLED_DIM_CONTRAST 0x01
#define OLED_DIM_AFTER_MS 5000
#define OLED_OFF_AFTER_MS 15000
#define OLED_RUNNING_OFF_AFTER_MS 65000
#define FINISHED_ALERT_MS 3000
