#pragma once

#include "driver/gpio.h"

#define APP_NAME "tickstone"

#define HABIT_COUNT 3
#define DEFAULT_DURATION_SECONDS (20 * 60)
#define MIN_DURATION_SECONDS 60
#define MAX_DURATION_SECONDS (99 * 60)

#define MAX7219_DIN_PIN GPIO_NUM_4
#define MAX7219_CLK_PIN GPIO_NUM_5
#define MAX7219_CS_PIN GPIO_NUM_6
#define MAX7219_DEVICE_COUNT 1
#define MAX7219_DEFAULT_INTENSITY 8

#define OLED_SDA_PIN GPIO_NUM_7
#define OLED_SCL_PIN GPIO_NUM_6
#define OLED_I2C_ADDRESS 0

#define HABIT_LED_1_PIN GPIO_NUM_15
#define HABIT_LED_2_PIN GPIO_NUM_16
#define HABIT_LED_3_PIN GPIO_NUM_17

#define BUTTON_LEFT_PIN GPIO_NUM_20
#define BUTTON_PLAY_PIN GPIO_NUM_8
#define BUTTON_RIGHT_PIN GPIO_NUM_9

#define BUTTON_DEBOUNCE_MS 40
#define BUTTON_LONG_PRESS_MS 700
#define TIMER_ADJUST_SECONDS 60
#define DISPLAY_DOT_BLINK_MS 500
#define DISPLAY_BOOT_TEST_MS 700
#define BUTTON_ACTIVE_LOOP_DELAY_MS 10
#define SESSION_LOOP_DELAY_MS 100
#define IDLE_LOOP_DELAY_MS 150
#define FINISHED_BLINK_MS 300
